%
O[05,22,11]  
([Travell Anthony] MAZE) 
(Startup Process)
T1 M06 	 		(Select tool)
G54 			(Use Work Offset G54)		
G90 G17 		(Safe Startup Line: Absolute Programming and Set the active plane as XY)
G00 X0. Y0.  	(Rapid Movement to 0 X,Yand Z axes in work offset)
G43 H01 Z1.0 	(Use Tool Offset #1)
(END Startup Process)

(GO TO THE STARTING POINT AND DROP THE PEN)
G01 [your xy start position] F12.0		(Go to start position and set Cutting Speed to 12 in/min)
M03 S1000		(Spin the pen for better precision)
Z0.0			(Move the pen to the paper)
G91       (Change to Incremental positioning)

(MOVEMENTS TO SOLVE THE MAZE)
X1.5 Y5 (north)
X-1.5 Y0 (east)
X0 Y7.5 (north)
X6.5 Y0 (weast)
X0 Y5 (north)
X4.5 Y0 (weast)
X0 Y-3 (south)
X7 Y0 (weast)
X0 Y2 (north)
X2 Y0 (weast)
X1 Y0 (north)
X0 Y1 (weast)
X1 Y0 (north)
X0 Y1 (weast)
(END SEQUENCE)
G00 G53 Z1.0	(Raise the pen) 
M30 			(End Program)
%
